image: gcr.io/bap-newera/nginx-php7:7.4

stages:
  - test
  - release

before_script:
  - mkdir ~/.ssh && chmod 700 ~/.ssh && ssh-keyscan git.sddproductions.com >> ~/.ssh/known_hosts
  - echo "$COMPOSER_GIT_AUTH" | base64 -d  > auth.json

########################################################################################################################
###   Tests                                                                                                          ###
########################################################################################################################

Unit Tests:
  stage: test
  script:
    - composer install --optimize-autoloader --ignore-platform-reqs --no-progress --no-suggest
    - php  -d zend_extension=xdebug.so  vendor/bin/phpunit  --coverage-text --colors=never

Tag Patch Version:
  stage: release
  only:
    - master
  except:
    - tags
    
  script:
  - GITLAB_TOKEN=$(cat auth.json | node -pe "JSON.parse(fs.readFileSync(0))['gitlab-token']['git.sddproductions.com']")

  - git clone --depth=1 https://oauth:$GITLAB_TOKEN@git.sddproductions.com/newera.systems/ci-templates.git
  - bash ci-templates/scripts/version-up.sh --apply --patch --release
    
  - git push --tags https://oauth:$GITLAB_TOKEN@git.sddproductions.com/${CI_PROJECT_PATH}
    
