services:
    extension.listener:
        class: SDD\UtilsBundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            # translatable sets locale after router processing
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
            # loggable hooks user username if one is in security context
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    core.twig.to_array_extension:
        class: SDD\UtilsBundle\Twig\ToArrayExtension
        tags:
            - { name: twig.extension }